name: MacOS Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          go test -v ./...

      - name: Create output directory
        run: mkdir -p build

      - name: Cross-compile for macOS
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o build/yask

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64-binary
          path: build/
